# Generated by Django 4.2.11 on 2024-03-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
