# Generated by Django 4.2.11 on 2024-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_datetime',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(null=True),
        ),
    ]
