# Generated by Django 4.2.11 on 2024-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reminder_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='sendAt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sendOn',
            field=models.TextField(default=''),
        ),
    ]
