# Generated by Django 4.2.11 on 2024-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_reminder_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='sendAt',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='sendOn',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
