# Generated by Django 4.2.11 on 2024-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_reminder_createdat_remove_reminder_sendat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sendingDate',
            field=models.TextField(null=True),
        ),
    ]
